server:
  port: 8888
 
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
security:
  basic:
    enabled: true # 开启基于HTTP basic的认证
  user:
    name: user  # 配置登录的账号是user
    password: password123 #配置登录的密码是password123